apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: j0lzblg4m-go
  janus-idp.io/tekton: j0lzblg4m-go
  backstage.io/kubernetes-id: j0lzblg4m-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: j0lzblg4m-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
